language: php

php:
  - '7.1'
  - '7.2'

cache:
  directories:
    - $HOME/.composer/cache

install:
  - composer install --no-interaction

notifications:
  email: false

sudo: false

script: vendor/bin/phpunit
